"""
whitelist.py — Known Safe Process Names
========================================
A comprehensive set of process names commonly found on Windows, Linux, and macOS.
Any process whose name (lowercased) is NOT in this set will be flagged as
"Unknown/Suspicious" by the monitor engine.

Maintainers: Add new entries in lowercase. The monitor compares via .lower().
"""

WHITELIST = {
    # ─── Windows System Processes ──────────────────────────────────────────────
    "system idle process",
    "system",
    "smss.exe",
    "csrss.exe",
    "wininit.exe",
    "services.exe",
    "lsass.exe",
    "lsaiso.exe",
    "svchost.exe",
    "fontdrvhost.exe",
    "dwm.exe",
    "winlogon.exe",
    "explorer.exe",
    "taskhostw.exe",
    "taskmgr.exe",
    "ctfmon.exe",
    "conhost.exe",
    "dllhost.exe",
    "sihost.exe",
    "runtimebroker.exe",
    "shellexperiencehost.exe",
    "startmenuexperiencehost.exe",
    "searchui.exe",
    "searchapp.exe",
    "searchhost.exe",
    "searchindexer.exe",
    "searchprotocolhost.exe",
    "searchfilterhost.exe",
    "securityhealthservice.exe",
    "securityhealthsystray.exe",
    "sgrmbroker.exe",
    "spoolsv.exe",
    "wudfhost.exe",
    "wmiprvse.exe",
    "msdtc.exe",
    "audiodg.exe",
    "registry",
    "memory compression",
    "ntoskrnl.exe",
    "cmd.exe",
    "powershell.exe",
    "pwsh.exe",
    "windowsterminal.exe",
    "wt.exe",
    "openssh.exe",
    "sshd.exe",
    "mstsc.exe",
    "rdpclip.exe",
    "dashost.exe",
    "smartscreen.exe",
    "applicationframehost.exe",
    "textinputhost.exe",
    "lockapp.exe",
    "comppkgsrv.exe",
    "gamebarpresencewriter.exe",
    "gameinputsvc.exe",
    "msedge.exe",
    "widgets.exe",
    "widgetservice.exe",
    "phoneexperiencehost.exe",
    "yourphone.exe",

    # ─── Windows Defender / Security ───────────────────────────────────────────
    "msmpeng.exe",
    "nissrv.exe",
    "mpcmdrun.exe",
    "wscsvc.exe",

    # ─── Windows Update / Installer ────────────────────────────────────────────
    "wuauclt.exe",
    "trustedinstaller.exe",
    "tiworker.exe",
    "musnotification.exe",
    "usoclient.exe",

    # ─── Common Browsers ──────────────────────────────────────────────────────
    "chrome.exe",
    "firefox.exe",
    "msedge.exe",
    "opera.exe",
    "brave.exe",
    "safari",
    "chromium",
    "iexplore.exe",
    "vivaldi.exe",
    "tor.exe",

    # ─── Development Tools ─────────────────────────────────────────────────────
    "python.exe",
    "python3.exe",
    "python",
    "python3",
    "pythonw.exe",
    "pip.exe",
    "pip3.exe",
    "node.exe",
    "node",
    "npm.exe",
    "npm",
    "npx.exe",
    "java.exe",
    "java",
    "javaw.exe",
    "javac.exe",
    "code.exe",
    "code",
    "devenv.exe",
    "pycharm64.exe",
    "pycharm.exe",
    "idea64.exe",
    "webstorm64.exe",
    "git.exe",
    "git",
    "git-remote-https.exe",
    "gh.exe",
    "docker.exe",
    "docker",
    "dockerd.exe",
    "docker-compose.exe",
    "dotnet.exe",
    "dotnet",
    "msbuild.exe",
    "cl.exe",
    "link.exe",
    "gcc",
    "g++",
    "make",
    "cmake",
    "rustc",
    "cargo",
    "go",
    "ruby",
    "perl",
    "php",
    "php-cgi",

    # ─── Communication / Productivity ──────────────────────────────────────────
    "slack.exe",
    "teams.exe",
    "ms-teams.exe",
    "discord.exe",
    "zoom.exe",
    "zoomit.exe",
    "skype.exe",
    "telegram.exe",
    "whatsapp.exe",
    "outlook.exe",
    "winword.exe",
    "excel.exe",
    "powerpnt.exe",
    "onenote.exe",
    "onenoteim.exe",
    "msaccess.exe",
    "notepad.exe",
    "notepad++.exe",
    "wordpad.exe",
    "mspaint.exe",
    "calc.exe",
    "snippingtool.exe",
    "screenclippinghost.exe",

    # ─── Media ─────────────────────────────────────────────────────────────────
    "spotify.exe",
    "vlc.exe",
    "vlc",
    "wmplayer.exe",
    "itunes.exe",
    "obs64.exe",
    "obs.exe",
    "audacity.exe",
    "gimp-2.10.exe",
    "gimp",
    "photoshop.exe",

    # ─── Utilities / Archivers / Misc ──────────────────────────────────────────
    "7zfm.exe",
    "7zg.exe",
    "winrar.exe",
    "winzip64.exe",
    "everything.exe",
    "filezilla.exe",
    "putty.exe",
    "winscp.exe",
    "curl.exe",
    "wget.exe",
    "robocopy.exe",
    "xcopy.exe",

    # ─── Antivirus / Security Vendors ──────────────────────────────────────────
    "avp.exe",
    "avpui.exe",
    "avgnt.exe",
    "avscan.exe",
    "mbam.exe",
    "mbamservice.exe",
    "bdagent.exe",
    "dwengine.exe",
    "norton.exe",
    "nortonsecurity.exe",

    # ─── Hardware / Drivers ────────────────────────────────────────────────────
    "nvcontainer.exe",
    "nvdisplay.container.exe",
    "nvspcaps64.exe",
    "atiesrxx.exe",
    "atieclxx.exe",
    "igfxem.exe",
    "igfxtray.exe",
    "realtek.exe",
    "rtkaudioservice64.exe",
    "razer synapse.exe",
    "razer synapse 3.exe",
    "logioptionsplus.exe",

    # ─── Linux System Processes ────────────────────────────────────────────────
    "init",
    "systemd",
    "systemd-journald",
    "systemd-logind",
    "systemd-udevd",
    "systemd-resolved",
    "systemd-timesyncd",
    "systemd-networkd",
    "kthreadd",
    "ksoftirqd",
    "kworker",
    "rcu_sched",
    "rcu_bh",
    "migration",
    "watchdog",
    "bash",
    "sh",
    "zsh",
    "fish",
    "dash",
    "cron",
    "crond",
    "atd",
    "sshd",
    "rsyslogd",
    "dbus-daemon",
    "polkitd",
    "accounts-daemon",
    "networkmanager",
    "wpa_supplicant",
    "dhclient",
    "dhcpcd",
    "avahi-daemon",
    "cupsd",
    "gdm",
    "gdm-session-worker",
    "lightdm",
    "sddm",
    "xorg",
    "xwayland",
    "gnome-shell",
    "gnome-session",
    "gnome-terminal-server",
    "kwin_wayland",
    "kwin_x11",
    "plasmashell",
    "pulseaudio",
    "pipewire",
    "pipewire-pulse",
    "wireplumber",
    "snapd",
    "unattended-upgr",
    "packagekitd",
    "apt",
    "apt-get",
    "dpkg",
    "yum",
    "dnf",
    "pacman",
    "nautilus",
    "thunar",
    "dolphin",
    "top",
    "htop",
    "ps",
    "grep",
    "awk",
    "sed",
    "cat",
    "less",
    "vim",
    "nano",
    "emacs",
    "tail",
    "journalctl",

    # ─── macOS System Processes ────────────────────────────────────────────────
    "launchd",
    "kernel_task",
    "windowserver",
    "dock",
    "finder",
    "systemuiserver",
    "loginwindow",
    "notificationcenter",
    "spotlight",
    "mds",
    "mds_stores",
    "mdworker",
    "mdworker_shared",
    "coreaudiod",
    "corelocationd",
    "coreservicesd",
    "cfprefsd",
    "distnoted",
    "trustd",
    "securityd",
    "opendirectoryd",
    "configd",
    "airportd",
    "bluetoothd",
    "usbd",
    "ioupsd",
    "timed",
    "fseventsd",
    "powerd",
    "thermald",
    "diskarbitrationd",
    "logd",
    "syslogd",
    "watchdogd",
    "apsd",
    "sharingd",
    "cloudd",
    "bird",
    "nsurlsessiond",
    "rapportd",
    "useractivityd",
    "suggestd",
    "photoanalysisd",
    "mediaaccessibilityd",
    "terminal",
    "iterm2",
    "activity monitor",
    "textedit",
    "preview",
    "mail",
    "messages",
    "facetime",
    "music",
    "photos",
    "xcode",
    "xcrun",
    "xcodebuild",
    "instruments",
    "simulator",
    "softwareupdated",
    "installd",

    # ─── Containerization / Virtualization ────────────────────────────────────
    "containerd",
    "runc",
    "crio",
    "podman",
    "kubectl",
    "kubelet",
    "virtualbox",
    "virtualboxvm",
    "vboxheadless",
    "vboxsvc",
    "vmware",
    "vmware-vmx",
    "qemu",
    "qemu-system-x86_64",
    "hyperv",
    "vmwp.exe",
    "vmcompute.exe",
    "vmms.exe",

    # ─── Database Servers ──────────────────────────────────────────────────────
    "mysqld",
    "postgres",
    "postgresql",
    "mongod",
    "redis-server",
    "memcached",
    "sqlservr.exe",

    # ─── Web / Application Servers ─────────────────────────────────────────────
    "nginx",
    "apache2",
    "httpd",
    "gunicorn",
    "uvicorn",
    "pm2",
    "iisexpress.exe",
    "w3wp.exe",

    # ─── Missing Windows Services / Apps / Developer Tools ─────────────────────
    "",  # System Idle Process sometimes appears as empty string
    "antigravity.exe",
    "msedgewebview2.exe",
    "intelcphdcpsvc.exe",
    "language_server_windows_x64.exe",
    "intelcphecisvc.exe",
    "ushupgradeservice.exe",
    "memcompression",
    "igfxcuiservice.exe",
    "backgroundtaskhost.exe",
    "wavessyssvc64.exe",
    "ravbg64.exe",
    "hostcontrolservice.exe",
    "hoststorageservice.exe",
    "hidmonitorsvc.exe",
    "warp-svc.exe",
    "dellffdpwmiservice.exe",
    "oneapp.igcc.winservice.exe",
    "whatsapp.root.exe",
    "esif_uf.exe",
    "tpmprovisioningservice.exe",
    "jhi_service.exe",
    "lms.exe",
    "mpdefendercoreservice.exe",
    "wmiregistrationservice.exe",
    "wslservice.exe",
    "apoint.exe",
    "unsecapp.exe",
    "aggregatorhost.exe",
    "apmsgfwd.exe",
    "apremote.exe",
    "hidfind.exe",
    "pyrefly.exe",
    "apntex.exe",
    "windowspackagemanagerserver.exe",
    "mousocoreworker.exe",
    "mysqld.exe",
    "mongod.exe",
    "useroobebroker.exe",
}
